spring:
  profiles:
    active: local

api:
  client:
    tiingo:
      url: https://api.tiingo.com
      auth-type: Token
      authorization-token: ${TIINGO_AUTH_TOKEN}
    yahoo-finance:
      url: http://finance.yahoo.com

server:
  port: 8080