spring:
  profiles:
    active: local
  datasource:
    hikari:
      max-lifetime: 240000
  jpa:
    #optional - show SQL statements in console.
    show-sql: true
    properties:
      javax:
        persistence:
          sharedCache:
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
            mode: ENABLE_SELECTIVE
      hibernate:
        javax:
          cache:
            missing_cache_strategy: create
        #optional - enable SQL statements formatting.
        format_sql: true
        #optional - generate statistics to check if L2/query cache is actually being used.
        generate_statistics: false
        cache:
          #required - turn on L2 cache.
          use_second_level_cache: false
          #optional - turn on query cache.
          use_query_cache: true
          region:
            #required - classpath to cache region factory.
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  batch:
    job:
      enabled: false

api:
  client:
    tiingo:
      url: https://api.tiingo.com
      auth-type: Token
      authorization-token: ${TIINGO_AUTH_TOKEN}
    yahoo-finance:
      url: http://finance.yahoo.com
    cnn:
      url: https://money.cnn.com
    fear-greed:
      url: https://production.dataviz.cnn.io
  security:
    enabled: false

server:
  port: 5000