spring:
  config:
    activate:
      on-profile: prod
  liquibase:
    default-schema: stock-data-service_prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: ${DATASOURCE_URL}?currentSchema=${spring.liquibase.default-schema}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}